name: "S3 Deploy Github Action"
description: "Deploy a directory to an S3 bucket using the AWS CLI."
author: andrewdex
runs:
  using: docker
  image: Dockerfile
branding:
  icon: upload-cloud
  color: blue
